# Generated by Django 4.2 on 2023-07-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentDeudInter',
            fields=[
                ('CodigoDeudInter', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
                ('Apellido', models.CharField(max_length=255)),
                ('MonDeuda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MonPago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('FechVenc', models.DateField()),
                ('Estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tbCuentaDeudInter',
            },
        ),
    ]
